version: '3.1'

services:
  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
